server:
  port: 8002
  display-name: bz_manage
spring:  
  profiles:  
    active: test
################################################测试环境配置#######################################################
---                                                       
spring:
  profiles: test
  dubbo: 
    application:
      name: manage-consumer
    base-package: com.bz.manage.service  # dubbo服务调用者所在的包  
    registry:
      address: 192.168.2.202:2181,192.168.2.205:2181                 # zookeeper注册中心的地址
      port: 2181                           # zookeeper注册中心的端口
    consumer:
      timeout: 60000 
      check: false                          # 服务启动时检查被调用服务是否可用
      retries: 2                           # 服务调用重试次数 
  explorationModel: true ##开发模式
  aop:
    proxy-target-class: true
  resources:
    static-locations:
      - classpath:/static/  
##########视图模板配置###############################################################################################
  freemarker:
    cache: true
    template-loader-path:
      - classpath:/templates/
    allow-request-override: false
    allow-session-override: false
    check-template-location: true
    charset: UTF-8
    enabled: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    prefer-file-system-access: true
    suffix: .ftl
    request-context-attribute: request
    settings:
      number_format: 0.######
      boolean_format: true,false
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      time_format: HH:mm:ss
      object_wrapper: freemarker.ext.beans.BeansWrapper
      whitespace_stripping: true
      tag_syntax: square_bracket
      template_update_delay: 0
      classic_compatible: true
###########数据源配置#######################
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.202:3306/bz_system?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false
    username: bztest
    password: bz123456
##########http配置########################
  http: 
   encoding:
      charset: UTF-8
##########json配置########################    
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
###########缓存配置#######################    
  cache:
    type: ehcache
    ehcache: 
      config: classpath:ehcache-shiro.xml